# Generated by Django 3.2.4 on 2023-03-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('disk_array', models.CharField(max_length=50)),
                ('nic', models.CharField(max_length=50)),
                ('video_card', models.CharField(max_length=50)),
                ('operation_system', models.CharField(max_length=50)),
                ('processor_clock', models.CharField(max_length=50)),
                ('total_phisical_memory', models.CharField(max_length=50)),
                ('ram_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'в обработке'), (2, 'выполнено'), (3, 'отменено')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_month', models.DecimalField(decimal_places=0, max_digits=10)),
                ('service_type', models.CharField(max_length=250)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ожидание'), (2, 'выполнено'), (3, 'отменено')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_part.service')),
            ],
        ),
    ]
